services:
    grossum_static_page.static_page.manager:
        class: %grossum_static_page.static_page.manager.class%
        arguments:
            - @grossum_core.entity_manager
            - %grossum_static_page.entity.static_page.class%
